# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  APPLICATION_ID: '392df650-a705-11ea-9f5d-61fe147bebd6'
  PACKAGE_NAME: 'firstdemoapp'
  VERSION: '0.0.1'
  HOSTNAME: 'tvfirstdemoapp.azurewebsites.net'

jobs:
  build:

    runs-on: ubuntu-latest

    #strategy:
    #  matrix:
    #    node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
      continue-on-error: true
    - run: gulp manifest
    - name: Upload a Build Artifact - App Manifest
      uses: actions/upload-artifact@v2
      with:
        # Artifact name
        name: App_Manifest # optional
        # A file, directory or wildcard pattern that describes what to upload
        path: ./package
    - name: Upload a Build Artifact - App
      uses: actions/upload-artifact@v2
      with:
        # Artifact name
        name: App # optional
        # A file, directory or wildcard pattern that describes what to upload
        path: ./dist
        
  deploy:

    runs-on: ubuntu-latest

    steps:
    - name: Build And Deploy
      id: builddeploy
      uses: Azure/static-web-apps-deploy@v0.0.1-preview
      with:
        azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_POLITE_POND_0FE40FB03 }}
        repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
        action: "upload"
        ###### Repository/Build Configurations - These values can be configured to match you app requirements. ######
        # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
        app_location: "/" # App source code path
        app_artifact_location: "dist" # Built app content directory - optional
          ###### End of Repository/Build Configurations ######
